
name: Update Jira Ticket

on:
  workflow_dispatch:
    inputs:
      sast_sca_scan_id:
        description: "Scan ID for SAST/SCA"
        default: ''
        type: string
      sast_sca_commit_id:
        description: "Commit ID for SAST/SCA"
        default: ''
        type: string
      csec_scan_id:
        description: "CSEC scan ID"
        default: ''
        type: string
      csec_commit_id:
        description: "Commit ID for CSEC"
        required: false
        type: string
      dast_scan_id:
        description: "DAST scan ID"
        default: ''
        type: string
      dast_commit_id:
        description: "Commit ID for DAST"
        default: ''
        type: string
      jira_issue:
        description: "Commit ID for DAST"
        default: ''
        type: string

jobs:
  run-dar-workflow:
    runs-on: ubuntu-latest

    env:
      CX_TOKEN: ${{ secrets.CX_TOKEN }}
      CX_TENANT_NAME: ${{ vars.CX_TENANT_NAME_NPROD }}
      CX_TENANT_IAM_URL: ${{ vars.CX_TENANT_IAM_URL_NPROD }}
      CX_TENANT_URL: ${{ vars.CX_TENANT_URL_NPROD }}
      JIRA_PAT: ${{ secrets.JIRA_PAT }}
      JIRA_PROJECT_ID: ${{ vars.JIRA_PROJECT_ID }}
      JIRA_URL: ${{ vars.JIRA_URL }}
      ISSUETYPE_ID: ${{ vars.ISSUETYPE_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DAR Script
        run: |
          python3 dw_update_jira_ticket.py \
            "${{ github.event.inputs.sast_sca_scan_id }}" \
            "${{ github.event.inputs.sast_sca_commit_id }}" \
            "${{ github.event.inputs.csec_scan_id }}" \
            "${{ github.event.inputs.csec_commit_id }}" \
            "${{ github.event.inputs.dast_scan_id }}" \
            "${{ github.event.inputs.dast_commit_id }}" \
            "${{ github.event.inputs.jira_issue }}"