
name: Update Jira Ticket

on:
  workflow_dispatch:
    inputs:
      scan_id:
        description: 'Checkmarx Scan ID'
        required: true
        default: ''
      commit_id:
        description: 'Commit ID'
        required: true
        default: ''
      jira_issue:
        description: 'Jira Issue ID'
        required: true
        default: ''

jobs:
  run-dar-workflow:
    runs-on: ubuntu-latest

    env:
      CX_EU_TOKEN: ${{ secrets.CX_EU_TOKEN }}
      CX_TENANT_NAME: ${{ vars.CX_TENANT_NAME }}
      CX_TENANT_IAM_URL: ${{ vars.CX_TENANT_IAM_URL }}
      CX_TENANT_URL: ${{ vars.CX_TENANT_URL }}
      JIRA_PAT: ${{ secrets.JIRA_PAT }}
      JIRA_PROJECT_ID: ${{ vars.JIRA_PROJECT_ID }}
      JIRA_URL: ${{ vars.JIRA_URL }}
      ISSUETYPE_ID: ${{ vars.ISSUETYPE_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Triage Script
        run: python3 dw_update_jira_ticket.py \
            "${{ github.event.inputs.scan_id }}" \
            "${{ github.event.inputs.commit_id }}" \
            "${{ github.event.inputs.jira_issue }}" \