
name: Echo Five Inputs and Outputs

on:
  workflow_dispatch:
    inputs:
      input1:
        description: 'Input 1'
        required: true
        default: 'one'
      input2:
        description: 'Input 2'
        required: true
        default: 'two'
      input3:
        description: 'Input 3'
        required: true
        default: 'three'
      input4:
        description: 'Input 4'
        required: true
        default: 'four'
      input5:
        description: 'Input 5'
        required: true
        default: 'five'

jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Inputs
        run: |
          echo "Input 1: ${{ github.event.inputs.input1 }}"
          echo "Input 2: ${{ github.event.inputs.input2 }}"
          echo "Input 3: ${{ github.event.inputs.input3 }}"
          echo "Input 4: ${{ github.event.inputs.input4 }}"
          echo "Input 5: ${{ github.event.inputs.input5 }}"